#!/bin/bash
export VITE_SUPABASE_URL='https://jdsojjjrxsknffuogdux.supabase.co'
export VITE_SUPABASE_ANON_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impkc29qampyeHNrbmZmdW9nZHV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyNjEwNjMsImV4cCI6MjA4NjgzNzA2M30.zPPzQev60bopgiBlenNAezIsYfNg8m5IMAigfsDGIhs'
cd web && npm run build
